/*
Copyright (c) 2017-2018 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dagon.graphics.materials.colorHUD;

import std.stdio;
import std.math;
import std.conv;

import dlib.core.memory;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.image.color;
import dlib.image.unmanaged;

import derelict.opengl;

import dagon.core.ownership;
import dagon.graphics.rc;
import dagon.graphics.texture;
import dagon.graphics.material;
import dagon.graphics.materials.generic;

class ColorHUDMaterialBackend: GLSLMaterialBackend
{
    private string vsText =
    q{
        #version 330 core
        precision highp float;

        uniform mat4 modelViewMatrix;
        uniform mat4 projectionMatrix;

        layout (location = 0) in vec2 va_Vertex;
        layout (location = 1) in vec2 va_Texcoord;

        out vec2 texCoord;

        void main()
        {
            texCoord = va_Texcoord;
            gl_Position = projectionMatrix * modelViewMatrix * vec4(va_Vertex, 0.0, 1.0);
        }
    };

    private string fsText = q{
        #version 330 core
        precision highp float;

        uniform vec4 color;
        uniform sampler2D diffuseTexture;

        in vec2 texCoord;

        out vec4 frag_color;

        void main()
        {
            frag_color = color*texture(diffuseTexture, texCoord);
        }
    };

    override string vertexShaderSrc() {return vsText;}
    override string fragmentShaderSrc() {return fsText;}

    GLint modelViewMatrixLoc;
    GLint projectionMatrixLoc;
    GLint colorLoc;
    GLint diffuseTextureLoc;

    this(Owner o)
    {
        super(o);

        modelViewMatrixLoc = glGetUniformLocation(shaderProgram, "modelViewMatrix");
        projectionMatrixLoc = glGetUniformLocation(shaderProgram, "projectionMatrix");
        colorLoc = glGetUniformLocation(shaderProgram, "color");
        diffuseTextureLoc = glGetUniformLocation(shaderProgram, "diffuseTexture");
    }

    final void setModelViewMatrix(Matrix4x4f modelViewMatrix){
        glUniformMatrix4fv(modelViewMatrixLoc, 1, GL_FALSE, modelViewMatrix.arrayof.ptr);
    }
    final void setAlpha(float alpha){ }
    final void setInformation(Vector4f information){
        //glUniform4fv(informationLoc, 1, information.arrayof.ptr);
        assert(0,"TODO?");
    }
    final void setColor(Vector4f color){
        glUniform4fv(colorLoc, 1, color.arrayof.ptr);
    }
    final void bindDiffuse(Texture diffuse){
        glActiveTexture(GL_TEXTURE0);
        diffuse.bind();
    }

    override void bind(GenericMaterial mat, RenderingContext* rc)
    {
        glUseProgram(shaderProgram);

        // Matrices
        glUniformMatrix4fv(modelViewMatrixLoc, 1, GL_FALSE, rc.modelViewMatrix.arrayof.ptr);
        glUniformMatrix4fv(projectionMatrixLoc, 1, GL_FALSE, rc.projectionMatrix.arrayof.ptr);

        if(mat){
            auto idiffuse = "diffuse" in mat.inputs;
            auto icolor = "color" in mat.inputs;

            // Texture 0 - diffuse texture
            if (idiffuse.texture is null)
            {
                Color4f color = Color4f(idiffuse.asVector4f);
                idiffuse.texture = makeOnePixelTexture(mat, color);
            }
            glActiveTexture(GL_TEXTURE0);
            idiffuse.texture.bind();
            if(icolor){
                Color4f color = Color4f(icolor.asVector4f);
                glUniform4fv(colorLoc, 1, color.arrayof.ptr);
            }else{
                glUniform4fv(colorLoc, 1, Color4f(1.0f,1.0f,1.0f,1.0f).arrayof.ptr);
            }
        }else{
            setColor(Color4f(1.0f,1.0f,1.0f,1.0f));
            glEnablei(GL_BLEND, 0);
            if(glBlendFunci){
                glBlendFunci(0, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
            }else glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        }
        glUniform1i(diffuseTextureLoc, 0);
    }

    override void unbind(GenericMaterial mat, RenderingContext* rc)
    {
        glUseProgram(0);
    }
}
