/*
Copyright (c) 2017-2018 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dagon.graphics.boneMesh;

import core.time: Duration;

import dlib.core.memory;
import dlib.geometry.triangle;
import dlib.math.vector;
import dlib.math.matrix;
import derelict.opengl;
import dagon.core.interfaces;
import dagon.core.ownership;

enum VertexAttrib
{
    Vertices0 = 0,
    Vertices1 = 1,
    Vertices2 = 2,
    Normals = 3,
    Texcoords = 4,
    BoneIndices = 5,
    Weights = 6,
    Pose = 7,
}

class BoneMesh: Owner, Drawable
{
    bool dataReady = false;
    bool canRender = false;

    // TODO: make these DynamicArrays
    Vector3f[][3] vertices;
    Vector3f[] normals;
    Vector2f[] texcoords;
    uint[3][] boneIndices;
    Vector3f[] weights;
    uint[3][] indices;

    Matrix4x4f[] pose; // (not owned)

    GLuint[3] vbo;
    GLuint vao = 0, nbo = 0, tbo = 0, eao = 0;
    GLuint bio = 0, weo = 0;

    this(Owner o)
    {
        super(o);
    }

    ~this()
    {
        foreach(i;0..3) if (vertices[i].length) Delete(vertices[i]);
        if (normals.length) Delete(normals);
        if (texcoords.length) Delete(texcoords);
        if (boneIndices.length) Delete(boneIndices);
        if (weights.length) Delete(weights);
        if (indices.length) Delete(indices);

        if (canRender)
        {
            glDeleteVertexArrays(1, &vao);
            foreach(i;0..3) glDeleteBuffers(1, &vbo[i]);
            glDeleteBuffers(1, &nbo);
            glDeleteBuffers(1, &tbo);
            glDeleteBuffers(1, &bio);
            glDeleteBuffers(1, &weo);
            glDeleteBuffers(1, &eao);
        }
    }

    final Vector3f getVertex(int i){
        return weights[i].x*(vertices[0][i]*pose[boneIndices[i][0]]) // (dlib matrix multipy uses wrong convention...)
            + weights[i].y*(vertices[1][i]*pose[boneIndices[i][1]])
            + weights[i].z*(vertices[2][i]*pose[boneIndices[i][2]]);
    }

    int opApply(scope int delegate(Triangle t) dg)
    {
        int result = 0;

        foreach(i, ref f; indices)
        {
            Triangle tri;

            tri.v[0] = getVertex(f[0]);
            tri.v[1] = getVertex(f[1]);
            tri.v[2] = getVertex(f[2]);
            tri.n[0] = normals[f[0]];
            tri.n[1] = normals[f[1]];
            tri.n[2] = normals[f[2]];
            tri.t1[0] = texcoords[f[0]];
            tri.t1[1] = texcoords[f[1]];
            tri.t1[2] = texcoords[f[2]];
            tri.normal = (tri.n[0] + tri.n[1] + tri.n[2]) / 3.0f;

            result = dg(tri);
            if (result)
                break;
        }

        return result;
    }

    void generateNormals()
    {
        if (normals.length == 0)
            return;

        normals[] = Vector3f(0.0f, 0.0f, 0.0f);

        foreach(i, ref f; indices)
        {
            Vector3f v0 = getVertex(f[0]);
            Vector3f v1 = getVertex(f[1]);
            Vector3f v2 = getVertex(f[2]);

            Vector3f p = cross(v1 - v0, v2 - v0);

            normals[f[0]] += p;
            normals[f[1]] += p;
            normals[f[2]] += p;
        }

        foreach(i, n; normals)
        {
            auto combinedTransform=(pose[boneIndices[i][0]]*weights[i].x+
                                    pose[boneIndices[i][1]]*weights[i].y+
                                    pose[boneIndices[i][2]]*weights[i].z);
            normals[i] = combinedTransform.invRotate(n.normalized);
        }
    }

    void prepareVAO()
    {
        if (!dataReady)
            return;

        if (!canRender)
        {
            foreach(i;0..3) glGenBuffers(1, &vbo[i]);
            glGenBuffers(1, &nbo);
            glGenBuffers(1, &tbo);
            glGenBuffers(1, &bio);
            glGenBuffers(1, &weo);
            glGenBuffers(1, &eao);
            glGenVertexArrays(1, &vao);
            canRender = true;
        }

        foreach(i;0..3){
            glBindBuffer(GL_ARRAY_BUFFER, vbo[i]);
            glBufferData(GL_ARRAY_BUFFER, vertices[i].length * float.sizeof * 3, vertices[i].ptr, GL_STATIC_DRAW);
        }

        glBindBuffer(GL_ARRAY_BUFFER, nbo);
        glBufferData(GL_ARRAY_BUFFER, normals.length * float.sizeof * 3, normals.ptr, GL_STATIC_DRAW);

        glBindBuffer(GL_ARRAY_BUFFER, tbo);
        glBufferData(GL_ARRAY_BUFFER, texcoords.length * float.sizeof * 2, texcoords.ptr, GL_STATIC_DRAW);

        glBindBuffer(GL_ARRAY_BUFFER, bio);
        glBufferData(GL_ARRAY_BUFFER, boneIndices.length * uint.sizeof * 3, boneIndices.ptr, GL_STATIC_DRAW);

        glBindBuffer(GL_ARRAY_BUFFER, weo);
        glBufferData(GL_ARRAY_BUFFER, weights.length * float.sizeof * 3, weights.ptr, GL_STATIC_DRAW);

        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, eao);
        glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.length * uint.sizeof * 3, indices.ptr, GL_STATIC_DRAW);

        glBindVertexArray(vao);
        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, eao);

        foreach(i;0..3){
            glEnableVertexAttribArray(VertexAttrib.Vertices0+i);
            glBindBuffer(GL_ARRAY_BUFFER, vbo[i]);
            glVertexAttribPointer(VertexAttrib.Vertices0+i, 3, GL_FLOAT, GL_FALSE, 0, null);
        }

        glEnableVertexAttribArray(VertexAttrib.Normals);
        glBindBuffer(GL_ARRAY_BUFFER, nbo);
        glVertexAttribPointer(VertexAttrib.Normals, 3, GL_FLOAT, GL_FALSE, 0, null);

        glEnableVertexAttribArray(VertexAttrib.Texcoords);
        glBindBuffer(GL_ARRAY_BUFFER, tbo);
        glVertexAttribPointer(VertexAttrib.Texcoords, 2, GL_FLOAT, GL_FALSE, 0, null);

        glEnableVertexAttribArray(VertexAttrib.BoneIndices);
        glBindBuffer(GL_ARRAY_BUFFER, bio);
        glVertexAttribIPointer(VertexAttrib.BoneIndices, 3, GL_UNSIGNED_INT, 0, null);

        glEnableVertexAttribArray(VertexAttrib.Weights);
        glBindBuffer(GL_ARRAY_BUFFER, weo);
        glVertexAttribPointer(VertexAttrib.Weights, 3, GL_FLOAT, GL_FALSE, 0, null);

        glBindVertexArray(0);
        glBindBuffer(GL_ARRAY_BUFFER, 0);
    }

    void update(Duration dt)
    {
    }

    void render(RenderingContext* rc)
    {
        if (canRender)
        {
            glUniformMatrix4fv(VertexAttrib.Pose, cast(int)pose.length, GL_FALSE, cast(float*)pose.ptr);
            glBindVertexArray(vao);
            glDrawElements(GL_TRIANGLES, cast(uint)indices.length * 3, GL_UNSIGNED_INT, cast(void*)0);
            glBindVertexArray(0);
        }
    }
}

